### ISSUE TITLE
[Feature Request] Option for 'plain' content type instead of json

### ISSUE THREAD

**Issue by JustinAiken** [evq/lutron-spy#1]
For [OpenHAB's REST API](https://github.com/openhab/openhab/wiki/REST-API), sending status updates or commands must be done as `text/plain` instead of `application/json`...  

For example, to turn on a light, you'd do something like:

``` javascript
 var request = $.ajax({
  type:       "POST",
  url:        "http://192.168.100.21:8080/rest/items/MyLight",
  data:       'on',
  headers:    { 'Content-Type': 'text/plain' }
});
```

(Taken from [this example](https://github.com/openhab/openhab/wiki/Samples-REST#jquery))

I'd work on a PR to enable it as an option, but I have neither a go nor a crazy compilation dev env...

**Comment by evq** [comment]
Hey @JustinAiken,

I've added an option in the config for content-type, does this work for you? I haven't cross compiled and tested it out on my Wink yet, but it passes the tests.

No crazy cross compilation environment is needed here :) Go is easy enough to install (mac: brew install go, ubuntu: apt-get install golang, etc; then one just needs to set up their GOPATH env variable), and goxc is as well (go get github.com/laher/goxc). The docker container buildroot was strictly for cross compiling slsnif and other more traditional C based goodies :p 

Also, I added some clarification to the README.md based on the issues you encountered with the remote serial numbers. Thanks for your help!

**Comment by evq** [comment]
On taking a closer look at the example you linked, it seems this might not work since I'm forcing data though a json serializer. I have it's type as an interface{} so one can do `"data":"on"` in the config, but when it is serialized the output string is `"on"`, with quotation marks included. Please let me know if this works with OpenHAB, I fear that it won't. :)

**Comment by JustinAiken** [comment]
Haha wow, that was fast - you had your PR open before brew even finished installing go for me!

Anyways, cross-complied this branch, but I get an error as soon as I run it:

``` bash
[root@flex-dvt bin]# ./lutron-spy-new
Illegal instruction
```

..and yeah, the JSON serializing would need to be turned off too, good point...

**Comment by evq** [comment]
Hey @JustinAiken.

I made a change such that if you make the data a string, it will not go through the serializer. So in your case I think `"data":"ON"` will now be sent as `ON`.

I just checked a cross compiled version and it worked fine on my wink. Can you run `file lutron-spy-new` just to check the executable type is correct. Just to make sure we're on the same page you used the binary from `$GOPATH/bin/lutron-spy-xc/snapshot/linux_arm/lutron-spy` right? I believe I had this issue before which as solved by settings an env variable `export GOARM=5`. Although I thought it should be set from the config file `.goxc.json`

**Comment by JustinAiken** [comment]
> I made a change such that if you make the data a string, it will not go through the serializer. So in your case I think "data":"ON" will now be sent as ON.

Ooh, that change looks like it will fix the actual POST'ing perfectly... :)

> Can you run file lutron-spy-new just to check the executable type is correct. Just to make sure we're on the same page you used the binary from $GOPATH/bin/lutron-spy-xc/snapshot/linux_arm/lutron-spy right? I believe I had this issue before which as solved by settings an env variable export GOARM=5

No luck:

``` bash
$ export GOPATH=/Users/jaiken/go
$ export GOARM=5
$ ~/go/bin/goxc                                                                                                                                                                                                                                       
[goxc:xc] 2015/04/15 22:10:02 Parallelizing xc for 22 platforms, using max 7 of 8 processors
[goxc:xc] 2015/04/15 22:10:05 Task xc succeeded

$ file /Users/jaiken/go/bin/lutron-spy-xc/snapshot/linux_arm/lutron-spy                                                                                                                                                                               
/Users/jaiken/go/bin/lutron-spy-xc/snapshot/linux_arm/lutron-spy: ELF 32-bit LSB executable, ARM, version 1 (SYSV), statically linked, not stripped

$ scp /Users/jaiken/go/bin/lutron-spy-xc/snapshot/linux_arm/lutron-spy winkhub:/bin/lutron-spy-newerx

$ ssh winkhub                                                                                                                                                                                                                                         
[root@flex-dvt ~]# /bin/lutron-spy-newerx
Illegal instruction
```

**Comment by evq** [comment]
Weird. Want to give my compiled version a shot? http://dropcanvas.com/tcem7

Not quite sure what the difference could be :/

**Comment by JustinAiken** [comment]
> Not quite sure what the difference could be :/

Hmm, maybe something with my brew-installed go... Looks like the complied file sizes are close, but not exactly the same:

Mine:     `5330344` bytes
Yours: `5324360` bytes

> Want to give my compiled version a shot? http://dropcanvas.com/tcem7

..and it works!  :grinning: 

Thanks for the great tool!  Finally I can get my home automatin'

**Comment by evq** [comment]
Sweet! Glad it's working for you. If you wouldn't mind, can you post your config or part of it so I can add it to the example for anyone else who is looking to use this with OpenHAB? Thanks!
