### ISSUE TITLE
Long-running deployment?

### ISSUE THREAD

**Issue by JustinAiken** [evq/lutron-spy#4]
- After you start it with `./slsnif /dev/ttySP2 -x | ./lutron-spy &`, is there a better way to stop it than `kill -9`ing the processes?
- Any thoughts on setting up an `init.d` files for autostart?

**Comment by evq** [comment]
Good idea. I think if we name the script something like `S59lutron-spy`, it will automatically be started and stopped by `rcS` and `rcK` on boot and shutdown.

The only question is if it makes sense to have it make a call to `S60lutron-core` on start and restart. I would lean toward not having it call out on start and on restart having it do a `/etc/init.d/S60lutron-core stop` before starting itself and `/etc/init.d/S60lutron-core start` after.

Also, it looks like the existing startup scripts for lutron-core, wink etc just make a call to killall when called with stop. I have just been doing a manual killall.
